#!/bin/sh

export HOMEBREW_CLEANUP_MAX_AGE_DAYS=1
export HOMEBREW_CLEANUP_PERIODIC_FULL_DAYS=1
export HOMEBREW_COLOR=true
export HOMEBREW_DISPLAY_INSTALL_TIMES=true
export HOMEBREW_INSTALL_BADGE="⚡️"
export HOMEBREW_NO_ENV_HINTS=true
export HOMEBREW_UPGRADE_GREEDY=true
